from django.core.management.base import BaseCommand

from catering.models import MenuItem, Venue


class Command(BaseCommand):
    help = "Populate the system with demo venues and menu recommendations only."

    def handle(self, *args, **options):
        venues = [
            {"name": "Grand Garden Hall", "location": "Makati City", "capacity": 180},
            {"name": "Riverside Pavilion", "location": "Pasig City", "capacity": 120},
            {"name": "Azure Ballroom", "location": "Taguig City", "capacity": 250},
        ]
        for venue_data in venues:
            Venue.objects.get_or_create(name=venue_data["name"], defaults=venue_data)

        menu_items = [
            {
                "name": "Sunrise Garlic Rice Plate",
                "category": "breakfast",
                "meal_type": "rice_meal",
                "description": "Garlic rice with eggs, tapa, and pickled vegetables.",
                "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
                "price": "145.00",
                "is_recommended": True,
            },
            {
                "name": "Golden Brioche French Toast",
                "category": "breakfast",
                "meal_type": "dessert",
                "description": "Soft brioche toast with fruit, syrup, and whipped cream.",
                "image_url": "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1200&q=80",
                "price": "135.00",
                "is_recommended": True,
            },
            {
                "name": "Classic Breakfast Platter",
                "category": "breakfast",
                "meal_type": "rice_meal",
                "description": "Longganisa, eggs, garlic rice, and fresh tomato relish.",
                "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
                "price": "155.00",
                "is_recommended": True,
            },
            {
                "name": "Morning Chicken Arroz Caldo",
                "category": "breakfast",
                "meal_type": "rice_meal",
                "description": "Comforting rice porridge with chicken, egg, and fried garlic.",
                "image_url": "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
                "price": "120.00",
                "is_recommended": False,
            },
            {
                "name": "Tropical Fruit Yogurt Cups",
                "category": "breakfast",
                "meal_type": "dessert",
                "description": "Layered yogurt, mango, pineapple, and granola parfait.",
                "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
                "price": "95.00",
                "is_recommended": False,
            },
            {
                "name": "Breakfast Club Sandwich",
                "category": "breakfast",
                "meal_type": "snack",
                "description": "Toasted sandwich with egg, ham, lettuce, and signature sauce.",
                "image_url": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=80",
                "price": "140.00",
                "is_recommended": False,
            },
            {
                "name": "Belgian Waffles with Berry Compote",
                "category": "breakfast",
                "meal_type": "dessert",
                "description": "Fluffy waffles finished with berries and cream.",
                "image_url": "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=1200&q=80",
                "price": "130.00",
                "is_recommended": True,
            },
            {
                "name": "Breakfast Sausage Skillet",
                "category": "breakfast",
                "meal_type": "viand",
                "description": "Savory sausage, potatoes, peppers, and eggs in a hot skillet.",
                "image_url": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=1200&q=80",
                "price": "165.00",
                "is_recommended": False,
            },
            {
                "name": "Pandesal and Spread Station",
                "category": "breakfast",
                "meal_type": "snack",
                "description": "Fresh pandesal with butter, jam, and cheese spreads.",
                "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
                "price": "85.00",
                "is_recommended": False,
            },
            {
                "name": "Breakfast Brew Coffee Service",
                "category": "breakfast",
                "meal_type": "drink",
                "description": "Freshly brewed coffee with creamers and sugar service.",
                "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
                "price": "70.00",
                "is_recommended": True,
            },
            {
                "name": "Fresh Mango Juice Bar",
                "category": "breakfast",
                "meal_type": "drink",
                "description": "Cold mango juice served in buffet dispensers.",
                "image_url": "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=1200&q=80",
                "price": "75.00",
                "is_recommended": False,
            },
            {
                "name": "Vegetable Omelet Station",
                "category": "breakfast",
                "meal_type": "viand",
                "description": "Made-to-serve omelets with cheese, peppers, and onions.",
                "image_url": "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1200&q=80",
                "price": "150.00",
                "is_recommended": True,
            },
            {
                "name": "Garden Fresh Pasta",
                "category": "lunch",
                "meal_type": "pasta",
                "description": "Creamy mushroom pasta finished with herbs and parmesan.",
                "image_url": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=80",
                "price": "180.00",
                "is_recommended": True,
            },
            {
                "name": "Harvest Chicken Rice Bowl",
                "category": "lunch",
                "meal_type": "rice_meal",
                "description": "Savory grilled chicken, buttered vegetables, and fragrant rice.",
                "image_url": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80",
                "price": "210.00",
                "is_recommended": True,
            },
            {
                "name": "Beef Caldereta Fiesta Tray",
                "category": "lunch",
                "meal_type": "viand",
                "description": "Rich tomato-based beef stew with vegetables and cheese.",
                "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
                "price": "240.00",
                "is_recommended": True,
            },
            {
                "name": "Herbed Fish Fillet",
                "category": "lunch",
                "meal_type": "viand",
                "description": "Pan-seared fish fillet with citrus herb butter sauce.",
                "image_url": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80",
                "price": "220.00",
                "is_recommended": False,
            },
            {
                "name": "Chicken Caesar Wrap",
                "category": "lunch",
                "meal_type": "snack",
                "description": "Grilled chicken wrap with romaine, parmesan, and caesar dressing.",
                "image_url": "https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=1200&q=80",
                "price": "160.00",
                "is_recommended": False,
            },
            {
                "name": "Roasted Vegetable Lasagna",
                "category": "lunch",
                "meal_type": "pasta",
                "description": "Layers of pasta, roasted vegetables, and creamy bechamel.",
                "image_url": "https://images.unsplash.com/photo-1619894991209-9f9694be045a?auto=format&fit=crop&w=1200&q=80",
                "price": "195.00",
                "is_recommended": True,
            },
            {
                "name": "Crispy Chicken Sliders",
                "category": "lunch",
                "meal_type": "snack",
                "description": "Mini buns with crispy chicken, slaw, and aioli.",
                "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
                "price": "170.00",
                "is_recommended": False,
            },
            {
                "name": "Butter Garlic Shrimp Rice",
                "category": "lunch",
                "meal_type": "rice_meal",
                "description": "Garlic shrimp served over steamed rice with vegetables.",
                "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80",
                "price": "230.00",
                "is_recommended": True,
            },
            {
                "name": "Mango Cooler Pitcher",
                "category": "lunch",
                "meal_type": "drink",
                "description": "Light tropical drink service for buffet and plated events.",
                "image_url": "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=1200&q=80",
                "price": "65.00",
                "is_recommended": False,
            },
            {
                "name": "Asian Noodle Salad",
                "category": "lunch",
                "meal_type": "pasta",
                "description": "Chilled noodles with sesame dressing and crisp vegetables.",
                "image_url": "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=1200&q=80",
                "price": "150.00",
                "is_recommended": False,
            },
            {
                "name": "Chicken Teriyaki Bento",
                "category": "lunch",
                "meal_type": "rice_meal",
                "description": "Sweet-savory chicken, rice, pickles, and side vegetables.",
                "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
                "price": "200.00",
                "is_recommended": True,
            },
            {
                "name": "Fresh Garden Lemonade",
                "category": "lunch",
                "meal_type": "drink",
                "description": "Refreshing lemonade with herbs and citrus slices.",
                "image_url": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=80",
                "price": "60.00",
                "is_recommended": False,
            },
            {
                "name": "Herb Roast Chicken",
                "category": "dinner",
                "meal_type": "viand",
                "description": "Roasted chicken with pan gravy and seasonal vegetables.",
                "image_url": "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1200&q=80",
                "price": "245.00",
                "is_recommended": True,
            },
            {
                "name": "Mango Graham Verrine",
                "category": "dinner",
                "meal_type": "dessert",
                "description": "Layered mango cream dessert in individual cups.",
                "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
                "price": "95.00",
                "is_recommended": False,
            },
            {
                "name": "Sea Salt Caramel Cheesecake",
                "category": "dinner",
                "meal_type": "dessert",
                "description": "Rich baked cheesecake finished with caramel drizzle.",
                "image_url": "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1200&q=80",
                "price": "120.00",
                "is_recommended": True,
            },
            {
                "name": "Braised Beef Short Plate",
                "category": "dinner",
                "meal_type": "viand",
                "description": "Slow-braised beef with roasted root vegetables and jus.",
                "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
                "price": "280.00",
                "is_recommended": True,
            },
            {
                "name": "Salmon with Lemon Butter",
                "category": "dinner",
                "meal_type": "viand",
                "description": "Pan-roasted salmon with silky lemon butter sauce.",
                "image_url": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80",
                "price": "275.00",
                "is_recommended": True,
            },
            {
                "name": "Truffle Mushroom Risotto",
                "category": "dinner",
                "meal_type": "rice_meal",
                "description": "Creamy risotto with mushrooms, parmesan, and truffle oil.",
                "image_url": "https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=1200&q=80",
                "price": "210.00",
                "is_recommended": False,
            },
            {
                "name": "Grilled Herb Pork Medallions",
                "category": "dinner",
                "meal_type": "viand",
                "description": "Tender pork medallions with rosemary glaze.",
                "image_url": "https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&w=1200&q=80",
                "price": "250.00",
                "is_recommended": False,
            },
            {
                "name": "Penne in Roasted Tomato Cream",
                "category": "dinner",
                "meal_type": "pasta",
                "description": "Penne pasta in a slow-roasted tomato and cream sauce.",
                "image_url": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=80",
                "price": "190.00",
                "is_recommended": False,
            },
            {
                "name": "Chocolate Lava Mini Cakes",
                "category": "dinner",
                "meal_type": "dessert",
                "description": "Warm chocolate cakes with soft molten centers.",
                "image_url": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=80",
                "price": "125.00",
                "is_recommended": True,
            },
            {
                "name": "Sparkling Citrus Mocktail",
                "category": "dinner",
                "meal_type": "drink",
                "description": "Elegant sparkling citrus beverage for formal dining.",
                "image_url": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=1200&q=80",
                "price": "80.00",
                "is_recommended": False,
            },
            {
                "name": "Roasted Garlic Mashed Potatoes",
                "category": "dinner",
                "meal_type": "rice_meal",
                "description": "Creamy side option with roasted garlic and butter.",
                "image_url": "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
                "price": "110.00",
                "is_recommended": False,
            },
            {
                "name": "Mediterranean Chicken Skewers",
                "category": "dinner",
                "meal_type": "viand",
                "description": "Char-grilled skewers with herbs, peppers, and yogurt dip.",
                "image_url": "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=80",
                "price": "225.00",
                "is_recommended": False,
            },
            {
                "name": "Berry Panna Cotta Cups",
                "category": "dinner",
                "meal_type": "dessert",
                "description": "Silky panna cotta topped with berry compote.",
                "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
                "price": "115.00",
                "is_recommended": False,
            },
        ]
        for menu_data in menu_items:
            MenuItem.objects.update_or_create(name=menu_data["name"], defaults=menu_data)

        self.stdout.write(self.style.SUCCESS("Venue and menu recommendation demo data loaded successfully."))
